### ISSUE TITLE
Export name issue with jest-mock while running Storybook

### ISSUE THREAD

**Issue by ElMenax** [eirslett/storybook-builder-vite#242]
Hello there,

When I install Vite then `storybook-builder-vite` with `npx sb@latest init --builder storybook-builder-vite`, the compilation works fine but then Storybook fails to start throwing this error:
<img width="662" alt="Screenshot 2022-02-16 at 11 33 44" src="https://user-images.githubusercontent.com/48448574/154247208-da7e3e95-d5b8-4807-aff6-986af41173a4.png">

I have tried to add `jest-mock` to the `optimizeDeps`, install the dependency but nothing works.

When I run `npx sb@next init --builder storybook-builder-vite`, I have a similar error with `acorn-jxs` which has a missing export as well.
I suspect that the issue is related to ESM and how the dependencies exports their methods.
Any clue or help to solve this issue?

Thanks!

**Comment by IanVS** [comment]
Are you using `@storybook/jest`?  I have had the same problem when trying to use that.  If not, what is pulling in jest-mock?  You should be able to `npm why jest-mock` to find out.

**Comment by axelkry** [comment]
I have the same issue :).. seems to be added by `@storybook/addon-interactions`
<img width="784" alt="Screenshot 2022-02-16 at 14 14 46" src="https://user-images.githubusercontent.com/93909567/154272067-204b1d58-f8fc-4516-bc06-3d4199fb81cd.png">

**Comment by IanVS** [comment]
I've had problems with `@storybook/addon-interactions` as well.  For now, I've just been using the `play` functions and importing directly from `@testing-library` modules instead of the instrumented storybook versions.  I'm hopeful that we'll be able to use the interactions addon at some point, but for now I think it's not ready for use in vite projects.

**Comment by kaminskypavel** [comment]
same error from a fresh install

**Comment by IanVS** [comment]
I think this is something that needs to be addressed in the interaction addon.  Would y'all mind giving a 👍 or adding any missing information to https://github.com/storybookjs/storybook/issues/17516?  

One other possible workaround (I don't really recommend it, and haven't tested it), could be to set `global = window`, since I believe that's what is failing inside of jest-mock (it tries to mock global, which vite does not polyfill like webpack.

**Comment by IanVS** [comment]
I've opened https://github.com/storybookjs/storybook/pull/17535 to address this issue, keep an eye on that if you'd like to know the current status.

**Comment by IanVS** [comment]
This should now be fixed in https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.43, if anyone would like to test it out.

**Comment by pastelmind** [comment]
I tried Storybook v6.5.0-alpha.44 and now get the following error:

```
Uncaught SyntaxError: The requested module '/node_modules/jest-mock/build/index.js?v=168864d3' does not provide an export named 'ModuleMocker'
```

![modulemocker-error](https://user-images.githubusercontent.com/29533079/156109240-125fb90c-bb6d-4bb3-ad51-6da51cd8ec03.png)

My dependencies are:

```
    "@storybook/addon-actions": "^6.5.0-alpha.44",
    "@storybook/addon-essentials": "^6.5.0-alpha.44",
    "@storybook/addon-interactions": "^6.5.0-alpha.44",
    "@storybook/addon-links": "^6.5.0-alpha.44",
    "@storybook/react": "^6.5.0-alpha.44",
    "@storybook/testing-library": "^0.0.9",
```

**Comment by IanVS** [comment]
Can you try adding jest-mock to your optimizeDeps.include?

**Comment by pastelmind** [comment]
@IanVS Just tried, but the `ModuleMocker` error persists :(

I'm testing with a freshly scaffolded project, by the way. My Vite config is:

```ts
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  optimizeDeps: {
    include: ["jest-mock"],
  },
  plugins: [react()],
});

```

**Comment by yotam-frid** [comment]
Experiencing this as well in a fresh project.

**Comment by IanVS** [comment]
I need to make a change in storybook, but in the meantime, you should be able to add a `.storybook/preview-head.html` with contents of:

```
<script>
  window.global = window;
</script>
```

In the reproduction in https://github.com/eirslett/storybook-builder-vite/issues/242#issuecomment-1055040000, I also needed to update vite to 2.8.6, run `npx sb@next upgrade --prerelease`, and then `rm -rf node_modules/.vite-storybook` to clear the cache.  After that, I'm able to load stories in that reproduction.

**Comment by IanVS** [comment]
I've opened https://github.com/storybookjs/storybook/pull/17614 to address the need to set `global` in my workaround above.

**Comment by shirakaba** [comment]
Just to add that I experience the above-mentioned issue on a fresh project:

> Uncaught SyntaxError: The requested module '/node_modules/jest-mock/build/index.js?v=168864d3' does not provide an export named 'ModuleMocker'

```sh
npm create vite@latest epg-service --template react-ts
npx sb@next init --builder storybook-builder-vite
```

I was unable to fix things by following IanVS's steps of:

1. Add the mentioned `.storybook/preview-head.html`:
    ```html
    <script>
      window.global = window;
    </script>
    ```
2. Add the following to my `vite.config.ts`:
    ```diff
    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'

    // https://vitejs.dev/config/
    export default defineConfig({
    +  optimizeDeps: {
    +    include: ["jest-mock"],
    +  },
      plugins: [react()]
    })
    ```
3. `npm install --save-dev vite@2.8.6`
4. `npx sb@next upgrade --prerelease`
5. `rm -rf node_modules/.vite-storybook`
6. `npm run storybook`

... However, the problem still persists. Here's my final package.json:

```json
{
  "name": "my-app",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@storybook/addon-actions": "^6.5.0-alpha.45",
    "@storybook/addon-essentials": "^6.5.0-alpha.45",
    "@storybook/addon-interactions": "^6.5.0-alpha.45",
    "@storybook/addon-links": "^6.5.0-alpha.45",
    "@storybook/react": "^6.5.0-alpha.45",
    "@storybook/testing-library": "0.0.9",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vitejs/plugin-react": "^1.0.7",
    "babel-loader": "^8.2.3",
    "storybook-builder-vite": "^0.1.17",
    "typescript": "^4.5.4",
    "vite": "^2.8.6"
  }
}
```

The only thing that I've found to improve the situation is kaminskypavel's suggestion to remove addon-interactions altogether (and I'm not sure what the consequences of that are):

```diff
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
-    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "storybook-builder-vite"
  }
}
```

**Comment by IanVS** [comment]
@shirakaba Do you happen to have a reproduction that I could take a look at?

**Comment by shirakaba** [comment]
@IanVS I've made one now:

https://github.com/shirakaba/storybook-jest-mock-issue-repro

On the branch `main`, the latest commit shows the results of:

```sh
npm create vite@latest storybook-jest-mock-issue-repro --template react-ts
cd storybook-jest-mock-issue-repro
npx sb@next init --builder storybook-builder-vite
```

On the branch `workaround`, the latest commit shows the results of the further steps 1-6 that I specified in the comment above (https://github.com/eirslett/storybook-builder-vite/issues/242#issuecomment-1058016078).

In both cases, they meet the same error:

> Uncaught SyntaxError: The requested module '/node_modules/jest-mock/build/index.js?v=168864d3' does not provide an export named 'ModuleMocker'

**Comment by IanVS** [comment]
Thanks @shirakaba that was helpful.  There's one more piece you need in your `workaround` branch (until I can make a PR to fix it in this repo and release a new version).

```
// .storybook/main.js

module.exports = {
  //...existing config
  viteFinal: async (config) => {
    config.optimizeDeps.include = [...(config.optimizeDeps?.include ?? []), 'jest-mock'];
    return config;
  },
};
```

**Comment by IanVS** [comment]
You should now be able to remove the explicit `jest-mock` if using [0.1.18](https://github.com/eirslett/storybook-builder-vite/releases/tag/v0.1.18).

**Comment by kaminskypavel** [comment]
just tested with the following deps 

```
         ...

        "@storybook/addon-actions": "^6.4.19",
        "@storybook/addon-essentials": "^6.4.19",
        "@storybook/addon-interactions": "^6.4.19",
        "@storybook/addon-links": "^6.4.19",
        "@storybook/jest": "^0.0.10",
        "@storybook/react": "^6.4.19",
        "@storybook/testing-library": "^0.0.9",
        "storybook-builder-vite": "^0.1.21",
        "vite": "^2.9.0-beta.4"
         ...

```
im still getting 


```
Uncaught ReferenceError: global is not defined
    at ../../node_modules/jest-mock/build/index.js (:6006/node_modules/.vite-storybook/deps/jest-mock.js?v=45d2dd06:597:37)
    at __require2 (:6006/node_modules/.vite-storybook/deps/chunk-3XETP6YP.js?v=45d2dd06:47:50)
    at :6006/node_modules/.vite-storybook/deps/jest-mock.js?v=45d2dd06:609:25

```


the error is still caused by `@storybook/addon-interactions` 🤷‍♂️

**Comment by IanVS** [comment]
This error is due to https://github.com/storybookjs/storybook/issues/15391.  Until we find a better way to solve it, you can create a `.storybook/preview-head.html` with contents of:

```html
<script>
  window.global = window;
</script>
```
